<?php
function orm_user() {
return array(
	"0" => array("param_column" => "user_id", "param_type" => "1"),
	"1" => array("param_column" => "email", "param_type" => "4"),
	"2" => array("param_column" => "passwd", "param_type" => "4"),
	"3" => array("param_column" => "name1", "param_type" => "4"),
	"4" => array("param_column" => "name2", "param_type" => "4"),
	"5" => array("param_column" => "furi1", "param_type" => "4"),
	"6" => array("param_column" => "furi2", "param_type" => "4"),
	"7" => array("param_column" => "sex", "param_type" => "4"),
	"8" => array("param_column" => "birthday", "param_type" => "9"),
	"9" => array("param_column" => "post", "param_type" => "4"),
	"10" => array("param_column" => "pref", "param_type" => "4"),
	"11" => array("param_column" => "address1", "param_type" => "4"),
	"12" => array("param_column" => "address2", "param_type" => "4"),
	"13" => array("param_column" => "address3", "param_type" => "4"),
	"14" => array("param_column" => "tel1", "param_type" => "4"),
	"15" => array("param_column" => "tel2", "param_type" => "4"),
	"16" => array("param_column" => "works", "param_type" => "4"),
	"17" => array("param_column" => "works_type", "param_type" => "4"),
	"18" => array("param_column" => "final_education", "param_type" => "4"),
	"19" => array("param_column" => "spouse", "param_type" => "4"),
	"20" => array("param_column" => "childeren", "param_type" => "4"),
	"21" => array("param_column" => "number_of_people_living_together", "param_type" => "1"),
	"22" => array("param_column" => "private_car", "param_type" => "4"),
	"23" => array("param_column" => "car_license", "param_type" => "4"),
	"24" => array("param_column" => "householde_income", "param_type" => "4"),
	"25" => array("param_column" => "housing_form", "param_type" => "4"),
	"26" => array("param_column" => "insert_datetime", "param_type" => "10"),
	"27" => array("param_column" => "update_datetime", "param_type" => "10"),
	"28" => array("param_column" => "stop_flg", "param_type" => "1"),
	"29" => array("param_column" => "delete_flg", "param_type" => "1"),
	"30" => array("param_column" => "point", "param_type" => "1"),
);
}
